name: garlic-bread
author: QuickScythe
version: ALPHA
description: This plugin adds Garlic bread to the game!
api-version: 1.2
api: Spigot
main: com.gugbmc.garlic.GarlicPlugin
commands:
   update:
      usage: /update
   item:
      usage: /item
      aliases:
      - i
   debug:
      usage: /debug